//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(FromQueryResult)]
pub struct AlbumModel {
    pub id: i64,

    pub name: String,

    // Album metadata
    pub sort_name: String,
    pub order_name: String,
    pub compilation: bool,

    // Album stats
    pub size: i64,
    pub song_count: i32,
    pub duration: i64,
    pub disk_numbers: Vec<i32>,
    pub year: i32,

    // Album artist
    pub artist_id: i64,
    pub artist_name: String,
    pub contributor_id: i64,
    pub contributor_name: String,
    pub contributor_role: String,
    pub contributor_sub_role: Option<String>,

    // album genre
    pub genre_id: i64,
    pub genre_name: String,
    pub sec_genre_id: i64,
    pub sec_genre_name: String,

    // Album annotation
    pub played_count: Option<i32>,
    pub played_at: Option<DateTime>,
    pub rating: Option<i32>,
    pub starred: Option<bool>,
    pub starred_at: Option<DateTime>,

    pub create_time: DateTime,
    pub update_time: DateTime,
}
