//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(FromQueryResult)]
pub struct ArtistModel {
    pub id: i64,

    pub name: String,

    // Artist metadata
    pub sort_name: String,
    pub order_name: String,

    // stat
    pub size: i64,
    pub album_count: i32,
    pub song_count: i32,
    pub duration: i64,

    // annotation
    pub played_count: Option<i32>,
    pub played_at: Option<DateTime>,
    pub rating: Option<i32>,
    pub starred: Option<bool>,
    pub starred_at: Option<DateTime>,

    // metadata
    pub updated_at: Option<DateTime>,

    pub role: String,
}
