//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(FromQueryResult)]
pub struct AudioFileModel {
    pub id: i64,

    pub name: String,
    pub sort_name: String,
    pub order_name: String,
    pub compilation: bool,

    pub album_id: i64,
    pub album_name: String,

    pub year: Option<i32>,

    pub track_number: Option<i32>,
    pub size: i64,
    pub duration: i64,
    pub bit_rate: i32,
    pub suffix: String,
    pub path: String,
    pub bpm: Option<i32>,
    pub channel_count: Option<i32>,
    pub sample_rate: Option<i32>,

    pub has_cover_art: bool,

    // Album artist
    pub artist_id: i64,
    pub artist_name: String,
    pub contributor_id: i64,
    pub contributor_name: String,
    pub contributor_role: String,
    pub contributor_sub_role: Option<String>,

    // album genre
    pub genre_id: i64,
    pub genre_name: String,
    pub sec_genre_id: i64,
    pub sec_genre_name: String,

    // Album annotation
    pub played_count: Option<i32>,
    pub played_at: Option<DateTime>,
    pub rating: Option<i32>,
    pub starred: Option<bool>,
    pub starred_at: Option<DateTime>,

    pub create_time: DateTime,
    pub update_time: DateTime,
}
