//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use domain::value::{AlbumId, GenreId};
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue::Set;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, DeriveEntityModel, Default)]
#[sea_orm(table_name = "album_genre")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    // AlbumIdentity field
    pub album_id: i64,

    pub genre_id: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct AlbumGenre {
    pub id: AlbumGenreId,
    pub album_id: AlbumId,
    pub genre_id: GenreId,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct AlbumGenreId(i64);

impl AlbumGenreId {
    pub fn as_i64(&self) -> i64 {
        self.0
    }
}

impl From<i64> for AlbumGenreId {
    fn from(id: i64) -> Self {
        Self(id)
    }
}

impl From<AlbumGenreId> for i64 {
    fn from(id: AlbumGenreId) -> Self {
        id.0
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Album,
    Genre,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Album => Entity::belongs_to(super::album::Entity)
                .from(Column::AlbumId)
                .to(super::album::Column::Id)
                .into(),
            Self::Genre => Entity::belongs_to(super::genre::Entity)
                .from(Column::GenreId)
                .to(super::genre::Column::Id)
                .into(),
        }
    }
}

impl Related<super::album::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Album.def()
    }
}

impl Related<super::genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genre.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for AlbumGenre {
    fn from(model: Model) -> Self {
        Self {
            id: AlbumGenreId::from(model.id),
            album_id: AlbumId::from(model.album_id),
            genre_id: GenreId::from(model.genre_id),
        }
    }
}

impl From<AlbumGenre> for ActiveModel {
    fn from(album_genre: AlbumGenre) -> Self {
        Self {
            id: Set(album_genre.id.into()),
            album_id: Set(album_genre.album_id.into()),
            genre_id: Set(album_genre.genre_id.into()),
        }
    }
}
