//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use domain::value::{ArtistId, GenreId};
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue::Set;
use serde::{Deserialize, Serialize};

//#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, DeriveEntityModel, Default)]
#[sea_orm(table_name = "artist_genre")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    // ArtistIdentity field
    pub artist_id: i64,

    pub genre_id: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ArtistGenre {
    pub id: ArtistGenreId,
    pub artist_id: ArtistId,
    pub genre_id: GenreId,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ArtistGenreId(i64);

impl ArtistGenreId {
    pub fn as_i64(&self) -> i64 {
        self.0
    }
}

impl From<i64> for ArtistGenreId {
    fn from(id: i64) -> Self {
        Self(id)
    }
}

impl From<ArtistGenreId> for i64 {
    fn from(id: ArtistGenreId) -> Self {
        id.0
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Artist,
    Genre,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Artist => Entity::belongs_to(super::artist::Entity)
                .from(Column::ArtistId)
                .to(super::artist::Column::Id)
                .into(),
            Self::Genre => Entity::belongs_to(super::genre::Entity)
                .from(Column::GenreId)
                .to(super::genre::Column::Id)
                .into(),
        }
    }
}
impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artist.def()
    }
}

impl Related<super::genre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genre.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for ArtistGenre {
    fn from(model: Model) -> Self {
        Self {
            id: ArtistGenreId::from(model.id),
            artist_id: ArtistId::from(model.artist_id),
            genre_id: GenreId::from(model.genre_id),
        }
    }
}

impl From<ArtistGenre> for ActiveModel {
    fn from(artist_genre: ArtistGenre) -> Self {
        Self {
            id: Set(artist_genre.id.into()),
            artist_id: Set(artist_genre.artist_id.into()),
            genre_id: Set(artist_genre.genre_id.into()),
        }
    }
}
