//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
use domain::library::{Library, ScanStatus};
use sea_orm::{entity::prelude::*, ActiveValue::Set};
use serde::{Deserialize, Serialize};

//#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, DeriveEntityModel, Default)]
#[sea_orm(table_name = "library")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub path_protocol: String,
    pub path_path: String,
    pub scan_status: i32,
    pub last_scan_at: chrono::NaiveDateTime,
    #[sea_orm(column_type = "BigInteger")]
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl From<Library> for Model {
    fn from(library: Library) -> Self {
        Model {
            id: library.id.into(),
            name: library.name,
            path_protocol: library.path.protocol,
            path_path: library.path.path,
            scan_status: library.scan_status.into(),
            last_scan_at: library.last_scan_at,
            version: library.version,
        }
    }
}

impl From<Model> for Library {
    fn from(model: Model) -> Self {
        use domain::value::{LibraryId, MediaPath};

        let path = MediaPath {
            protocol: model.path_protocol,
            path: model.path_path,
        };

        let mut library = Library::new(LibraryId::from(model.id), model.name, path);
        library.scan_status = model.scan_status.try_into().unwrap_or(ScanStatus::Idle);
        library.last_scan_at = model.last_scan_at;
        library.version = model.version;

        library
    }
}

impl From<Library> for ActiveModel {
    fn from(library: Library) -> Self {
        ActiveModel {
            id: Set(library.id.into()),
            name: Set(library.name),
            path_protocol: Set(library.path.protocol),
            path_path: Set(library.path.path),
            scan_status: Set(library.scan_status.into()),
            last_scan_at: Set(library.last_scan_at),
            version: Set(library.version),
        }
    }
}
