//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use domain::library::LibraryItem;
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue::Set;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, DeriveEntityModel, Default)]
#[sea_orm(table_name = "library_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "BigInteger")]
    pub library_id: i64,
    // MediaPath split for storage
    pub path_protocol: String,
    pub path_path: String,
    #[sea_orm(column_type = "BigInteger")]
    pub size: i64,
    pub suffix: String,
    pub mtime: chrono::NaiveDateTime,
    pub atime: chrono::NaiveDateTime,
    pub state: i32, // LibraryItemState enum as i32
    pub file_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Library,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Library => Entity::belongs_to(super::library::Entity)
                .from(Column::LibraryId)
                .to(super::library::Column::Id)
                .into(),
        }
    }
}

impl Related<super::library::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Library.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for LibraryItem {
    fn from(model: Model) -> Self {
        use domain::library::LibraryItemState;
        use domain::value::FileType;
        use domain::value::MediaPath;

        let state = LibraryItemState::try_from(model.state).unwrap();
        let file_type = FileType::try_from(model.file_type.clone()).unwrap();
        LibraryItem {
            id: domain::value::LibraryItemId::from(model.id),
            library_id: domain::value::LibraryId::from(model.library_id),
            path: MediaPath {
                protocol: model.path_protocol,
                path: model.path_path,
            },
            size: model.size,
            suffix: model.suffix,
            mtime: model.mtime,
            atime: model.atime,
            state,
            file_type,
        }
    }
}

impl From<LibraryItem> for ActiveModel {
    fn from(library_item: LibraryItem) -> Self {
        let state = library_item.state.into();
        let file_type = library_item.file_type.into();
        ActiveModel {
            id: Set(library_item.id.as_i64()),
            library_id: Set(library_item.library_id.as_i64()),
            path_protocol: Set(library_item.path.protocol),
            path_path: Set(library_item.path.path),
            size: Set(library_item.size),
            suffix: Set(library_item.suffix),
            mtime: Set(library_item.mtime),
            atime: Set(library_item.atime),
            state: Set(state),
            file_type: Set(file_type),
        }
    }
}
