//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod album;
//pub mod album_genre;
pub mod annotation;
pub mod artist;
//pub mod artist_genre;
pub mod audio_file;
pub mod cover_art;
pub mod genre;
pub mod library;
pub mod library_item;
pub mod participant;
pub mod play_queue;
pub mod play_queue_item;
pub mod player;
pub mod playlist;
pub mod playlist_entry;
pub mod system_config;
pub mod transcoding;
pub mod user;
