//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::album::Entity as Album;
//pub use super::annotation::Entity as Annotation;
pub use super::artist::Entity as Artist;
pub use super::audio_file::Entity as AudioFile;
pub use super::genre::Entity as Genre;
//pub use super::player::Entity as Player;
//pub use super::property::Entity as Property;
//pub use super::transcoding::Entity as Transcoding;
//pub use super::user::Entity as User;
